### ISSUE TITLE
InCommon: add the <mdrpi:PublicationInfo> extension element

### ISSUE THREAD

**Issue by trscavo** [iay/mdq-server-docker#15]
Add an `<mdrpi:PublicationInfo>` extension element to the `/entities` aggregate as well as the `/entities/collection:idps` aggregate. Should we add this extension element to each signed entity descriptor as well? In any case, we need to determine an appropriate value of the `publisher` XML attribute.

**Comment by iay** [comment]
The `mdq-server` implementation doesn't distinguish between aggregates and single responses, they all pass through the same processing as a collection of some number of items. During the rendering phase and just before the signature step, there's a stage that wraps a collection of more than one item with an `<EntitiesDescriptor>`. So the simplest solution is to just apply the same processing to all responses and to add the same `<mdrpi:PublicationInfo>` to everything. You'd just need to tell me what value you want for `@publisher` for that. I'd suggest either making it the same as the `@registrationAuthority` value or picking something deployment-specific like `http://mdq-beta.incommon.org/global`.

Because we can do conditional processing in MDA pipelines, it would be *possible* to change the `PublicationInfo` information in static ways depending on arbitrary properties of the collection, for example just adding it to aggregates. I don't see much advantage in this, though, so I'd suggest going for the simplest approach to start with.

**Comment by trscavo** [comment]
The InCommon TAC is scheduled to discuss this issue (and other MD-RPI-related issues) at its next meeting on February 19, 2015. Perhaps we should hold off doing anything until then?

**Comment by iay** [comment]
I think that was a meeting I had to miss for one reason or another. Was there any progress towards a decision?

**Comment by trscavo** [comment]
Discussion at the meeting focused on the `<mdrpi:RegistrationInfo>` element. We didn't discuss the `<mdrpi:PublicationInfo>` element at all.

I suggest we let this stew for awhile and come back to it at a later (unspecified) time. If you would prefer to close the issue for now, that's fine too.

**Comment by iay** [comment]
It's fine to leave the question open indefinitely.

**Comment by iay** [comment]
The InCommon beta deployment was shut down some time ago, so I'm just going to close this.
